
service: hello-go

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128

package:
  exclude:
  - ./**
  include:
  - ./bin/**

functions:
  hello-world:
    handler: bin/hello-go
    events:
    - http:
        path: /hello
        method: get
    - http:
        path: /
        method: get